language: ruby
bundler_args: --without development
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - jruby-19mode
  - rbx
addons:
  code_climate:
    repo_token: c2fc6d91a4f61b11207fc145b35c379fc6b3514c74f2a53905dd4d21405332d8
